In [1]:
## Problem statement

## data collected from hospital
## Now the doctor will check whether the delivery is through caseasarian or not
## caseasarian is through operation and not normal delivery

In [2]:
## Problem  is if new lady is getting admitted - we have to predict if delivery will be caesarian or not
## This is a classification problem
## 0 indicates no Caesarian and 1 is Caesarian
## Age, delivery, Blood Pressure, Heart Problem are features
## Caesarian is category / label --0 is class which represent no Caesarian case and 1 rperesent Caesarian case

In [3]:
## For using this data we need to load the data
## We will use below libraries

In [4]:
## Importing Libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [7]:
df  = pd.read_csv("caesarian.csv")  ## loading data

In [8]:
df

Age  DeliveryNumber  DeliveryTime  BloodPressure  HeartProblem  Caesarian
0    22               1             0              2             0          0
1    26               2             0              1             0          1
2    26               2             1              1             0          0
3    28               1             0              2             0          0
4    22               2             0              1             0          1
..  ...             ...           ...            ...           ...        ...
75   27               2             1              1             0          0
76   33               4             0              1             0          1
77   29               2             1              2             0          1
78   25               1             2              0             0          1
79   24               2             2              1             0          0

[80 rows x 6 columns]

In [9]:
type(df)

pandas.core.frame.DataFrame

In [10]:
df.shape   ## Shape

(80, 6)

In [11]:
df.ndim ## No of dimensions since dataframe

2

In [18]:
df  ## Index given by pandas internally

Age  DeliveryNumber  DeliveryTime  BloodPressure  HeartProblem  Caesarian
0    22               1             0              2             0          0
1    26               2             0              1             0          1
2    26               2             1              1             0          0
3    28               1             0              2             0          0
4    22               2             0              1             0          1
..  ...             ...           ...            ...           ...        ...
75   27               2             1              1             0          0
76   33               4             0              1             0          1
77   29               2             1              2             0          1
78   25               1             2              0             0          1
79   24               2             2              1             0          0

[80 rows x 6 columns]

In [12]:
df.dtypes

Age               int64
DeliveryNumber    int64
DeliveryTime      int64
BloodPressure     int64
HeartProblem      int64
Caesarian         int64
dtype: object

In [13]:
## Now we want to separate features and labels
#- We will use iloc method.

In [16]:
labels = df.iloc[:, -1].values  

In [17]:
## -1 is for last column either row, item, column. we can also use 5
## .values skip index part gerated by pandas. 

In [18]:
features = df.iloc[:, 0:5].values  ## features = df.iloc[:, 0:-1].values  can also be done

In [19]:
labels  ## 0 means Non Caesarian and 1 means Caesarian

array([0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1,
       0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1,
       1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0], dtype=int64)

In [20]:
features

array([[22,  1,  0,  2,  0],
       [26,  2,  0,  1,  0],
       [26,  2,  1,  1,  0],
       [28,  1,  0,  2,  0],
       [22,  2,  0,  1,  0],
       [26,  1,  1,  0,  0],
       [27,  2,  0,  1,  0],
       [32,  3,  0,  1,  0],
       [28,  2,  0,  1,  0],
       [27,  1,  1,  1,  0],
       [36,  1,  0,  1,  0],
       [33,  1,  1,  0,  0],
       [23,  1,  1,  1,  0],
       [20,  1,  0,  1,  1],
       [29,  1,  2,  0,  1],
       [25,  1,  2,  0,  0],
       [25,  1,  0,  1,  0],
       [20,  1,  2,  2,  0],
       [37,  3,  0,  1,  1],
       [24,  1,  2,  0,  1],
       [26,  1,  1,  1,  0],
       [33,  2,  0,  0,  1],
       [25,  1,  1,  2,  0],
       [27,  1,  0,  0,  1],
       [20,  1,  0,  2,  1],
       [18,  1,  0,  1,  0],
       [18,  1,  1,  2,  1],
       [30,  1,  0,  1,  0],
       [32,  1,  0,  2,  1],
       [26,  2,  1,  1,  1],
       [25,  1,  0,  0,  0],
       [40,  1,  0,  1,  1],
       [32,  2,  0,  2,  1],
       [27,  2,  0,  1,  1],
       [26,  2

In [21]:
## Now we will train test split for splitting data
## We already have method in sklearn.

In [22]:
## train_test_split method will divide into labels, features
## four parts features_train, features_test, labels_train,labels_test.

In [23]:
from sklearn.model_selection import train_test_split  

In [24]:
features_train,features_test,labels_train, labels_test =  train_test_split(features, labels, test_size = 0.25) 
## test_size = 0.25 will keep 75% for training and 25% for testing

In [38]:
## test_size = 0.25 can ce be kept 10 20 30....But ideal is near 20-25-15%
## features_train,features_test,labels_train, labels_test are naming conventions for variable name
## other variables name can also be used
## test_size = 0.25 is key value pair

In [25]:
len(features)  

80

In [26]:
len(features_train)  

60

In [27]:
len(features_test)  

20

In [28]:
len(labels)

80

In [29]:
len(labels_train)  

60

In [30]:
len(labels_test)  

20

In [33]:
zip(features_train,labels_train)  ## x is in features_train and y is in labels_train

In [34]:
tuple(zip(features_train,labels_train)) ## we have both features and labels together
## This is training data and can be done for test data also

((array([27,  2,  1,  1,  0], dtype=int64), 0),
 (array([29,  2,  1,  2,  0], dtype=int64), 1),
 (array([33,  1,  1,  1,  0], dtype=int64), 0),
 (array([28,  3,  0,  1,  0], dtype=int64), 1),
 (array([32,  2,  0,  0,  0], dtype=int64), 1),
 (array([23,  1,  1,  1,  0], dtype=int64), 0),
 (array([25,  1,  1,  2,  0], dtype=int64), 0),
 (array([20,  1,  0,  2,  1], dtype=int64), 1),
 (array([27,  2,  0,  1,  1], dtype=int64), 1),
 (array([25,  1,  0,  0,  0], dtype=int64), 1),
 (array([36,  1,  1,  2,  0], dtype=int64), 1),
 (array([21,  1,  0,  0,  0], dtype=int64), 1),
 (array([31,  2,  2,  1,  0], dtype=int64), 0),
 (array([29,  1,  2,  0,  1], dtype=int64), 1),
 (array([29,  2,  0,  1,  1], dtype=int64), 1),
 (array([21,  2,  1,  0,  1], dtype=int64), 1),
 (array([33,  3,  2,  1,  1], dtype=int64), 0),
 (array([22,  1,  0,  2,  0], dtype=int64), 0),
 (array([25,  1,  0,  1,  0], dtype=int64), 0),
 (array([27,  1,  0,  0,  1], dtype=int64), 1),
 (array([26,  2,  1,  1,  1], dtype=int6

In [ ]:
## third parameter is random state which is not used for practice

In [ ]:
## Now our problem is Classification for which we will use KNN  

In [42]:
from sklearn.neighbors import KNeighborsClassifier ## KNeighborsClassifier is class

In [43]:
classifier = KNeighborsClassifier(n_neighbors=5,p=2)  ## We need to create object by calling constructor

In [ ]:
# p=2 , Euclidean and 1  = Manhattan

#What Does Constructor Mean? 
# A constructor is a special method of a class or structure in object-oriented programming 
# that initializes a newly created object of that type. 
# Whenever an object is created, the constructor is called automatically.
# https://www.techopedia.com/definition/5656/constructor

In [44]:
classifier

KNeighborsClassifier()

In [47]:
classifier.fit(features_train, labels_train)  ## Training of model

KNeighborsClassifier()

In [53]:
labels_pred = classifier.predict(features_test) ## Prediction of model

In [49]:
features_test  ## For this test data model has predicted, 20 rows 20 prediction

array([[33,  2,  0,  0,  1],
       [26,  2,  2,  1,  0],
       [29,  2,  0,  0,  1],
       [35,  1,  1,  0,  0],
       [31,  1,  2,  2,  1],
       [27,  1,  0,  2,  1],
       [18,  1,  1,  2,  1],
       [18,  1,  0,  1,  0],
       [27,  1,  1,  1,  0],
       [32,  2,  0,  2,  1],
       [37,  3,  0,  1,  1],
       [22,  1,  2,  2,  0],
       [22,  2,  0,  1,  0],
       [25,  1,  2,  0,  0],
       [31,  1,  0,  1,  0],
       [30,  1,  0,  1,  0],
       [22,  1,  0,  1,  0],
       [29,  1,  2,  0,  1],
       [26,  2,  1,  1,  0],
       [33,  1,  1,  0,  0]], dtype=int64)

In [54]:
labels_pred ## Predicted label

array([1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1],
      dtype=int64)

In [50]:
labels_test  # Original test label we compare with Predicted label

array([1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1],
      dtype=int64)

In [1]:
## For [33,  2,  0,  0,  1], model predicted 1 and orignal is 0

In [2]:
## Now we will import confusion_matrix to check accuracy

In [57]:
from sklearn.metrics import confusion_matrix

In [58]:
confusion_matrix(labels_test, labels_pred)

array([[2, 5],
       [8, 5]], dtype=int64)

In [ ]:
## confusion matrix always in classification only
## we get different vaslues for confusion_matrix because train_test_split randomly split data

## Now change n_neighbors = 7 and p=1 Manhattan distance

In [ ]:
## from sklearn.neighbors import KNeighborsClassifier ## KNeighborsClassifier is class 
## Not done above since already imported.

In [60]:
classifier = KNeighborsClassifier(n_neighbors=7,p=1)  ## We need to create object by calling constructor

In [61]:
classifier.fit(features_train, labels_train)  ## Training of model

KNeighborsClassifier(n_neighbors=7, p=1)

In [62]:
labels_pred = classifier.predict(features_test) ## Prediction of model

In [63]:
labels_test  # Original test label we compare with Predicted label

array([1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1],
      dtype=int64)

In [64]:
from sklearn.metrics import confusion_matrix

In [65]:
confusion_matrix(labels_test, labels_pred)

array([[3, 4],
       [6, 7]], dtype=int64)

In [72]:
from sklearn.metrics import accuracy_score
accuracy_score(labels_test, labels_pred)

0.5

In [73]:
## Accuracy is 50%

In [74]:
## Accuracy = (7+3) / (3 + 4 + 6 + 7)

## We can check for single prediction

In [67]:
x = [33,  2,  0,  0,  1] ## x is list

In [68]:
x = np.array(x)

In [69]:
x.shape  ## It has 5 rows. It is 1 dimensional. but we need 2 dimensional data since training is 2 dimensional data

(5,)

In [70]:
x = x.reshape(1,5)

In [71]:
classifier.predict(x)  ## We get 1 - Caesarian , this is single prediction

array([1], dtype=int64)